### PR TITLE
Send command v2

### PR DESCRIPTION
**Pull request by netmindz**
Sending commands, but now with v2 of the Android Home Assistant library so we can use select drop-down for mode, pump speed etc

### CODE REVIEW

**Comment by netmindz** [comment]
I am getting pretty close to merging this down into main. 

Can't test pumps as I have the wrong FB values at the moment and onPumpSwitchStateChanged and onModeSwitchStateChanged can't handle when you need to go "down" off the bottom of the list of choices to loop back to the option you need.

Other than that, I think we are in a pretty good position. 

Would be nice to remove the resend command hack, but that can be its own PR

Will need to update the install guide to add pin5, remove the level shifter and add a suitable disclaimer about trying your ESP

**Comment by netmindz** [comment]
onPumpSwitchStateChanged tested ok for single speed, do you have dual speed @tmjo ?

**Comment by netmindz** [comment]
I've tried to write onModeSwitchStateChanged, but is still buggy

**Comment by tmjo** [comment]
> onPumpSwitchStateChanged tested ok for single speed, do you have dual speed @tmjo ?

Yes, mine is a dual speed. I'll try to do some more testing this week.

**Pull request merged**
