### PR TITLE
Pin5

### PR DESCRIPTION
**Pull request by netmindz**
Use level shifter and pin5 to break on the serial data into each message

### CODE REVIEW

**Comment by netmindz** [comment]
I had made an error with earlier testing. Pin5 will not allow you to break rs485 stream into messages, I had also been playing around with using pin5 and either pin2 or pin4 to see if it was i2c data.
Once that was eliminated and I swapped to using a pin purely for indication of the "framing"/start-end, I had actually been using either pin2 or pin4 not pin5
Pin5 is purely to indicate which port is the target of the query

**Comment by netmindz** [comment]
If I start reading data when pin5 goes low, then continue reading until pin4 or pin5 go HIGH, then i get valid messages.
Unfortunately, to send an FB command it appears pin4 must be LOW

So I can read messages, but I'm then too late to send my FB reply to the FA message I just read

Reading fixed length might be a different approach, but then we will need to also discard any data that isn't the start of a message or you can slip put of sync. This would feel very hacky and error prone, so this would be a point of last resort given at least one of the pins is there to help us break up the RS485 into the bits we need

**Comment by netmindz** [comment]
When I  try and apply the same code pattern to the main sensor app I see a different issue, where we actually see pin5 low when the next bytes we read are FB - the effect of some form of buffering maybe?

18:39:25.709 -> Unknown message length for fb
18:39:25.709 -> Unknown message length for fb
18:39:25.930 -> fa142d Short
18:39:25.995 -> ae0d01 Short
18:39:26.059 -> Unknown message length for fb
18:39:26.059 -> Unknown message length for fb
18:39:26.127 -> ae0d02 Short
18:39:26.191 -> fa142d Short
18:39:26.252 -> ae0d03 Short
18:39:26.316 -> fa142d Short
18:39:26.380 -> ae0d00 Short
18:39:26.444 -> fa142d Short
18:39:26.509 -> ae0d01 Short
18:39:26.578 -> fa142d Short
18:39:26.703 -> Unknown message length for fb
18:39:26.704 -> Unknown message length for fb
18:39:26.929 -> Unknown message length for fb
18:39:26.929 -> Unknown message length for fb
18:39:27.057 -> fa142d Short

**Comment by TiSiAi** [comment]
> When I try and apply the same code pattern to the main sensor app I see a different issue, where we actually see pin5 low when the next bytes we read are FB - the effect of some form of buffering maybe?

yes it's a problem.
I havent this


only FA... frame or AE... frame

**Comment by netmindz** [comment]
Not sure 100%, but I think the level shifter I was using was adding a delay. I'm now risking direct connection as some people say the ESP32 is 5v tolerant and getting more luck with timings of when to sent commands. Really want to find what the best low-latency option is for safe connection of pin5 to the ESP without risking blowing them up not getting a timing lag

**Comment by netmindz** [comment]
Pretty sure now it was the level shifter that I was using that was the issue. Pin5 was the key to easier handling of the data and to know when to sent

**Pull request closed without merging**
