### PR TITLE
Pump speed states 

### PR DESCRIPTION
**Pull request by caldog20**
I hope you don't mind, I did run clang-format to get a standard formatting since some of the formatting was different across the codebase. 

I made a small adjustment to support having 2 dual speed pumps. I wanted to open so others could verify.

### CODE REVIEW

**Comment by netmindz** [comment]
Generally better to have single-purpose PRs, but I'll let you off this time ;)

I only have a single speed pumps, code looks sane, so I'm tempted to just merge

**Comment by caldog20** [comment]
> Generally better to have single-purpose PRs, but I'll let you off this time ;)
> 
> I only have a single speed pumps, code looks sane, so I'm tempted to just merge

Sorry, that's why I split it into 2 different commits. :P

**Comment by tmjo** [comment]
Will see if I can test this today or tomorrow.

**Comment by netmindz** [comment]
Any luck testing @tmjo ?

**Comment by tmjo** [comment]
> Any luck testing @tmjo ?

No, sorry. It's been raining sheep and cows here lately, so I wasn't able to test yet. Forecast looking better, so hope to do it soon.

**Comment by netmindz** [comment]
I find people in the UK who don't own a tub think they are best when the weather is warm, I always say that if anything when the weather is cold is actually better, that any day is a tub day - unless it's raining ;)

**Comment by tmjo** [comment]
> I find people in the UK who don't own a tub think they are best when the weather is warm, I always say that if anything when the weather is cold is actually better, that any day is a tub day - unless it's raining ;)

True, true. Even light rain can be nice, but not while debugging with a computer :) How are you guys testing, do you have the serial cable going inside, or a long usb-cable? Or just staying outside as well? I was looking at some 10m usb-extensions, but not sure if it will work.

**Comment by tmjo** [comment]
Guys,

I've been fooling myself it seems. My Pump1 is two-speed, but my other pump is probably not Pump2. It is labelled Aux on my panel, and from my old notes I found out it gives value 'c' in the location before pump (result.substring(12, 13). I'll double check, but that's what I found in some older loggings.

@caldog20; Could you do a double check of the values? I have a strong feeling it is all bitcoded, and it would make perfect sense except for values '4' (would make sense if it was Pump1 Off, Pump2 Low) and '7' (which in my narrow minded logic would give pump1 both low and high at same time). Perhaps I am wrong, but it would be good to double check.

```
0		00000000	All off			ok
1		00000001	Pump1 Low		ok
2		00000010	Pump1 High		ok
4		00000100	?			Would make sense if Pump1 Off, Pump2 Low
6		00000110	Pump1 High Pump2 Low	ok
7		00000111	Pump1 Off Pump2 Low	Is this correct? If bitwise 11 would mean both on and off for pump1
8		00001000	Pump1 Off Pump2 High	ok
9		00001001	Pump1 Low, Pump2 High	ok
a		00001010	Pump1 High, Pump2 High	ok
```

**Comment by caldog20** [comment]
I think the difference here is if you have a dedicated circulation pump?
Mine doesn’t, so pump 1 is technically the circ pump and cannot be off if
pump2 is on at any speed. My dip switch for circulation pump is disabled
since I only have pump 1 and pump 2. Could this be it?

**Comment by caldog20** [comment]
I will still double check but right low this is the status I am using for my setup and it reads properly. But it could still be wrong so I will decode it again and double check.

**Comment by caldog20** [comment]
@tmjo Yeah you are correct. I am not sure where the "7" came from. This is infact bitcoded using 4 bits for the pump1/pump2 states. I will make the appropriate changes so you can test.

**Comment by tmjo** [comment]
That is awesome! I believe that is true for some of the other bytes as well such as status and heater/light byte at least. It could make the parsing easier and faster, IMHO we should at some point refactor to use less Strings and more raw bytes and just check byte for byte (without "string'ing" in between) and in some cases just check specific bits.

For instance I have noted:

```
1	00000001	STD		ok
2	00000010	ECO		ok
4	00000100	SLEEP		ok
9	00001001	STD CIRC	ok
a	00001010	STD CLEAN	Check? Should be ECO in Circ?
b	00001011	STD in ECO	ok? Should be STD in ECO Circ
c	00001100	SLEEP CIRC	ok
3	00000011	STD in ECO	ok
```

which leads me to believe that b4 may be circulation pump running. But not sure.

**Comment by netmindz** [comment]
Sounds like we are happy for me to merge this in.

As for string Vs btye Vs bit, would definitely welcome a PR tidying some of that up. Might well help the reboots I see sometimes that I think might be memory related. String was just easiest option when copying and pasting during initial experiments

**Pull request merged**
