### PR TITLE
Add tempsensor from Fahrenheit

### PR DESCRIPTION
**Pull request by tmjo**

### CODE REVIEW

**Comment by netmindz** [comment]
I propose we replace existing temp sensor with reading this value, especially as the whole way i was trying to differentiate between target temp and actual temp is quite hacky

**Comment by tmjo** [comment]
Agreed. My thinking was to implement it separately for a while just to monitor the behaviour over time, then probably do what you comment here if everything seems logical. There seems to be a difference between display value and the F-value, but it could be some internal rounding or whatever.

**Comment by tmjo** [comment]
Sure, I can do that. But should we add a new sensor to show what is in the display then?

**Comment by netmindz** [comment]
I was thinking of coming back to that as part of when we are able to send commands. E.g when moving through the menus remotely, seeing what would be on the panel at the time

**Comment by netmindz** [comment]
I kind of have that already with the status field

**Comment by netmindz** [comment]
superseded by https://github.com/netmindz/balboa_GL_ML_spa_control/tree/temp-from-F

**Pull request closed without merging**
