### PR TITLE
Update project to Android Home Assistant - version 2

### PR DESCRIPTION
**Pull request by netmindz**

### CODE REVIEW

**Comment by netmindz** [comment]
Are you able to test this branch to see if this still works as before with the updated library @tmjo ?

**Comment by tmjo** [comment]
Still didn't get everything running to test this, but did some reading. Did you see the limitation stuff in the [docs ](https://dawidchyrzynski.github.io/arduino-home-assistant/documents/library/device-types.html)? Could that be why no data is showing on all sensors?

**Comment by netmindz** [comment]
Ah no, I hadn't seen the limit of 6, we definitely have more than that. I did remove some of the entities that become redundant, but still think over 6 remain

**Comment by netmindz** [comment]
I am getting some updates now, like raw data and uptime, but not seeing the status of the light come through, so might have missed something here in updating to be a switch not sensor

**Comment by netmindz** [comment]
Making much better progress now. Still a few controls to add and wire up to send the right commands and stuff but getting there

**Comment by netmindz** [comment]
Note that I'm actually now working on the send-command-queue-v2 branch now

**Pull request closed without merging**
